### PR TITLE
PDAL, pdal-python, and deps

### PR DESCRIPTION
**Pull request by c-gr34sl3y**
For INC1383181

**PDAL**
 `PDAL-2.5.5-foss-2022a.eb` (about 30 mins build time)
_Deps_
`GDAL-3.5.0-foss-2022a.eb` - from upstream
`PostgreSQL-14.4-GCCcore-11.3.0.eb` - from upstream
`Xerces-C++-3.2.3-GCCcore-11.3.0.eb` - from upstream (plugin)

After building, it would be useful to add something to the apps page about the test data being available through `$PDAL_TEST_DATA`

**pdal-python**
`pdal-python-3.2.3-foss-2022a.eb`

* [x] Assigned to reviewer

Default:
* [ ] EL8-icelake
* [ ] EL8-cascadelake
* [ ] EL8-haswell

### CODE REVIEW

**Comment by c-gr34sl3y** [comment]
In the CMakeLists for the pdal-python build the following setting
find_package(Python3 COMPONENTS Interpreter ${DEVELOPMENT_COMPONENT} NumPy REQUIRED)
would <not> find the $EBROOTPYTHON at all (or numpy) but would see the venv python.

After some faffing, i removed the following from https://github.com/PDAL/python/blob/3.2.3/CMakeLists.txt and it finds them. Not sure these settings work well with cmake 3.23.1

# Python-finding settings
set(Python3_FIND_STRATEGY "LOCATION")
set(Python3_FIND_REGISTRY "LAST")
set(Python3_FIND_FRAMEWORK "LAST")

# Development vs. Development.Module
# https://cmake.org/cmake/help/latest/module/FindPython3.html?highlight=Development.Module
if (${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.18.0" AND NOT APPLE)
    set(DEVELOPMENT_COMPONENT "Development.Module")
else()
    set(DEVELOPMENT_COMPONENT "Development")
endif()

**Comment by c-gr34sl3y** [comment]
After building, it would be useful to add something to the apps page about the test data being available through `$PDAL_TEST_DATA`

**Review by gyear — COMMENTED** [review]
Since GDAL, PostgresSQL and Xerces are all upstream do we need to add their easyconfigs?

**Comment by c-gr34sl3y** [comment]
@gyear -- removed the upstream easyconfigs from this PR.

**Review by orbsmiv — APPROVED** [review]
lgtm

**Pull request merged**
